export const mockData = {
  stats: [
    {
      title: "Total Kampanye",
      value: "18",
      description: "+4 dari bulan lalu",
      trend: "up",
    },
    {
      title: "Total Revenue",
      value: "Rp 2.450.000.000",
      description: "+21.5% dari bulan lalu",
      trend: "up",
    },
    {
      title: "Total Spend",
      value: "Rp 680.000.000",
      description: "+12.1% dari bulan lalu",
      trend: "up",
    },
    {
      title: "Avg. ROAS",
      value: "3.60x",
      description: "+0.45 dari bulan lalu",
      trend: "up",
    },
  ],
  chartData: [
    { name: "Jan", revenue: 450, spend: 180 },
    { name: "Feb", revenue: 520, spend: 210 },
    { name: "Mar", revenue: 890, spend: 350 },
    { name: "Apr", revenue: 1250, spend: 420 },
    { name: "May", revenue: 1840, spend: 580 },
    { name: "Jun", revenue: 2450, spend: 680 },
  ],
  campaigns: [
    {
      id: "1",
      name: "Promo Ramadhan & Lebaran 2026",
      status: "RUNNING",
      budget: "Rp 350.000.000",
      revenue: "Rp 1.120.000.000",
      startDate: "2026-03-01",
      endDate: "2026-04-15",
      roi: "3.20x",
    },
    {
      id: "2",
      name: "Gajian Sale - Mei",
      status: "APPROVED",
      budget: "Rp 120.000.000",
      revenue: "Rp 0",
      startDate: "2026-05-25",
      endDate: "2026-05-31",
      roi: "0.00x",
    },
    {
      id: "3",
      name: "Launching Produk Baru: Kopi Gula Aren",
      status: "COMPLETED",
      budget: "Rp 85.000.000",
      revenue: "Rp 340.000.000",
      startDate: "2026-01-10",
      endDate: "2026-02-10",
      roi: "4.00x",
    },
    {
      id: "4",
      name: "Harbolnas 11.11 Pre-Order",
      status: "DRAFT",
      budget: "Rp 450.000.000",
      revenue: "Rp 0",
      startDate: "2026-11-01",
      endDate: "2026-11-11",
      roi: "0.00x",
    },
  ],
  influencers: [
    {
      name: "Raffi Ahmad",
      handle: "@raffinagita1717",
      platform: "Instagram",
      followers: "75M",
      revenue: "Rp 850.000.000",
      roas: "5.2x",
      status: "Active",
    },
    {
      name: "Tasya Farasya",
      handle: "@tasyafarasya",
      platform: "Instagram",
      followers: "6.5M",
      revenue: "Rp 420.000.000",
      roas: "4.8x",
      status: "Active",
    },
    {
      name: "Fadil Jaidi",
      handle: "@fadiljaidi",
      platform: "Instagram",
      followers: "10M",
      revenue: "Rp 610.000.000",
      roas: "6.1x",
      status: "Active",
    },
    {
      name: "Deddy Corbuzier",
      handle: "@mastercorbuzier",
      platform: "YouTube",
      followers: "22M",
      revenue: "Rp 240.000.000",
      roas: "2.5x",
      status: "Completed",
    },
    {
      name: "Jerome Polin",
      handle: "@jeromepolin",
      platform: "TikTok",
      followers: "12M",
      revenue: "Rp 180.000.000",
      roas: "3.1x",
      status: "Active",
    },
  ],
};
